version: '3.8'

# Inspired by https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres
    restart: always
    env_file: .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '2345:80'
    volumes:
      - ${PGADMIN_VOLUME}:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - "postgres"

networks:
  postgres:
    driver: bridge